### ISSUE TITLE
File posted without owner's permission

### ISSUE THREAD

**Issue by SobyDamn** [I-Am-The-Great/BombSquadServerLinux64bitLatestModified#4]
data/bsMap.py contains codes posted without the permission of owner(me)
@I-Am-The-Great is not allowed to post in public

**Comment by I-Am-The-Great** [comment]
Lul, you sharing your code [here](https://github.com/SobyDamn/bombsquad-server-mods/blob/master/textformap.py) and forbid me to share your code! I am just spreading your work for good reason.

**Comment by SobyDamn** [comment]
You didn't asked for permission.

**Comment by I-Am-The-Great** [comment]
Well you did first share your code, so it makes available to all users your code then what matter if I do or not share, you already are sharing your code and even it is open source, then if you want me or anyone to ask permission to you, you would have added LICENSE in your [repository](https://github.com/SobyDamn/bombsquad-server-mods), because of its lack and open source code no one will ever think to ask permissions from you.

**Comment by I-Am-The-Great** [comment]
Every good repository has a LICENSE to state what things people can do with the code.

**Comment by TheMikirog** [comment]
@I-Am-The-Great So by that extension, everyone is allowed to just take stuff from Joyride Modpack without permission, even though I made models and sounds myself and credited those who contributed (with their permission).

If you post something out there, no matter where, **by default** it's their stuff and you can't take it without permission unless stated otherwise. It also depends on what kind of website it has been posted. Mods from ModDB for example always belong to the creators and there are rarely cases of stolen content. Mods are also in the grey area where they can still use copyrighted characters and stuff under fair use.

You can claim all you want that "all you did was make it open source", but that's still stealing. It's basically saying "this code has been hidden somwhere by the original owner, so I made it available to anyone. I only made it more public". It sounds pretty scummy.
You can also apply it to compilation modpacks and stolen videos on YouTube. Instead of saying "I stole JRMP and claimed it as mine" they just said "I just made it available to more people". I despise that kind of thinking.

@I-Am-The-Great should've been more careful and ask first before sharing the mod. If the LICENSE file doesn't exist, assume that it's not open-source or public domain. It's their property.
And again, **unless stated otherwise**.

**Comment by I-Am-The-Great** [comment]
Uhm, @TheMikirog well I understand your opinion and agree with it but in the start, I asked and he gave me the code then he made that code open source and never said me to not share that code, then how would I guess that he would get sad, or angry or whatever if I shared his code; well from now after reading your comment I will take care of all the things I do; but @SobyDamn should also include LICENSE so that no else silly kid like me gets confused.

**Comment by SobyDamn** [comment]
Use my files to share it in public

**Comment by I-Am-The-Great** [comment]
> 
> 
> Use my files to share it in public

Then please say it simply like now.

**Comment by I-Am-The-Great** [comment]
> 
> 
> Use my files to share it in public

Wait till I change the files, in new commit then.

**Comment by I-Am-The-Great** [comment]
By the way, @TheMikirog I want to ask you an offtopic question, may I?

**Comment by TheMikirog** [comment]
@I-Am-The-Great Sure thing. If I'm not able to answer all of your questions here, I always have my Discord.

**Comment by I-Am-The-Great** [comment]
So in the last, I want forgiveness from @TheMikirog and @SobyDamn and permission from @SobyDamn, and discord ID of @TheMikirog.

**Comment by TheMikirog** [comment]
@I-Am-The-Great If that makes you feel better.
TheMikirog#4697

**Comment by I-Am-The-Great** [comment]
> 
> 
> @I-Am-The-Great If that makes you feel better.
> TheMikirog#4697

Thank you and do you forgive me?

**Comment by SobyDamn** [comment]
I am not going to give permission.

**Comment by I-Am-The-Great** [comment]
> 
> 
> I am not going to give permission.

K then as you wish.

**Comment by TheMikirog** [comment]
@I-Am-The-Great Of course I do. Everyone makes mistakes and pointing them out is the only way to improve as people.

**Comment by SobyDamn** [comment]
And yeah i forgive you too

**Comment by I-Am-The-Great** [comment]
K then, now let's close this issue.

**Comment by I-Am-The-Great** [comment]
:cry: @TheMikirog I am unable to message you due to Clyde bot.
